version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: workforce-container
    environment:
      POSTGRES_USER: workforce
      POSTGRES_PASSWORD: workforce
      POSTGRES_DB: workforce
    ports:
      - "6432:5432"
    networks:
      - workforce-network
    volumes:
      - workforce-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@workforce.com
      PGADMIN_DEFAULT_PASSWORD: workforce
    ports:
      - "5050:80"
    networks:
      - workforce-network
    depends_on:
      - postgres

networks:
  workforce-network:

volumes:
  workforce-data: